### PR TITLE
[WIP] Autotools update

### PR DESCRIPTION
**Pull request by hanetzer**
Currently a WIP, but I've got a rough conversion to modern autotools conventions and usage in
a separate clone from upstream hg. Currently going through and making logical changes to have
a proper history if we do end up sending patches upstream.

Eventual goal is a modernized build and the ability to build against either SDL or SDL2.
A SDL build may not be of use to mkxp, but we shouldn't be selfish, no?

### CODE REVIEW

**Comment by Ancurio** [comment]
I'm trusting you that this still configures fine after these changes :)

**Comment by hanetzer** [comment]
NONONO, undo! WIP

**Comment by Ancurio** [comment]
Why did you make a PR then? =/

**Comment by hanetzer** [comment]
To let you know what's going on, get opinions and feedback, etc.

**Comment by Ancurio** [comment]
I force pushed the reversion

**Comment by hanetzer** [comment]
Ok, now with that being said, do you have any comments or suggestions as to the 'best'
way to modernize this? Feature's you'd like to see added, etc?

**Comment by Ancurio** [comment]
> Feature's you'd like to see added, etc?

There's one thing I tried implementing but failed in the past: **discovery of ogg/vorbis library via pkg-config**. Currently the script uses some hardcoded header paths which make this really annoying to setup. This was a long time ago though, so my memory is a bit hazy.

**Comment by hanetzer** [comment]
Well, I did get that working. Its almost entirely pkg-config now, check out #9 .
The only bit that isn't pkg-config is I directly look for libSDL2 because autoconf
was trying to link `-lmingw32` and `-lSDL2main`, which are only needed for
executables, not libraries.

**Pull request merged**
